import sys
sys.path.insert(0, '.')

# Final deduplicated tournament word list (194 unique words)
words_raw = """ADDRESS,APOSTROPHE,BADMINTON,BALLOON,BEAUTIFUL,BEDROOM,BELIEVE,BUSINESSMAN,GROCERIES,CASTLE,
CHILDREN,CHOCOLATE,CLIMBING,COUNTRYSIDE,CUPBOARD,CYCLING,DAUGHTER,DELICIOUS,DIFFERENT,DINING ROOM,
DISGUSTING,DOLPHIN,DOWN TOWN,EARPHONES,ELECTRICIAN,ELEPHANT,ENGINEER,EVENING,EXPENSIVE,EXERCISE,
FACTORY,FASHIONABLE,FEBRUARY,FIRE FIGHTER,FRIENDSHIP,FURNITURE,GRANDDAUGHTER,HAIRDRESSER,HOMEWORK,ADDRESS,
INFORMATION,INSTRUMENT,INTERESTING,INTRODUCING,JACKET,JUNGLE,KEYBOARD,KNOWLEDGE,LABORATORY,LANGUAGES,
LIBRARY,LIFESTYLE,LUNCHTIME,MAGAZINE,MEDICINE,MICROWAVE OVEN,MONKEY,MOUNTAINS,MUSEUM,NATIONALITY,
NECKLACE,NEIGHBORHOOD,NEWSPAPER,NOTEBOOK,OFFICE BUILDING,OPPOSITE,PHARMACY,POST OFFICE,PRINCIPAL,PROPERTY,
PSYCHOLOGY,QUESTIONS,RAINBOW,RECOGNIZE,REFRIGERATOR,REMEMBER,SALES ASSISTANT,SAXOPHONE,SCISSORS,SENTENCES,
SHOPPING,SHOULDER,SKATEBOARDING,SNOWBOARDING,SPEAKING,BUBBLE SPEECH,STATEMENTS,STOMACHACHE,STRAWBERRY,SUPERMARKET,
SURPRISING,SWIMMING,TELEVISION,THAILAND,THEATER,TOMATOES,TOMORROW,TOOTHBRUSH,TRAIN STATION,UMBRELLA,
UNDERSTAND,UNITED KINGDOM,VEGETABLES,VIDEOGAMES,WAITRESS,WARNING,WEATHER,WEDNESDAY,STEERING WHEEL,WHISTLE,
BUSINESSMAN,WARMING,SCIENTIST,POLICE OFFICER,THIRTY THREE,MOVIE THEATER,GRANDFATHER,GUINEA PIG,FASCINATING,GRANDCHILDREN,
HAIRBRUSH,WAKING UP,AIRPLANE,LIBRARY,GREEN POINT,IMAGES,BATHROOM,NOODLES,HANDLES,BORING,
AMAZING,DISLIKE,EXPLANATION,EVERYWHERE,QUICKLY,TIRING,WHEELCHAIR,HOLIDAYS,UNCOUNTABLE,SWEATER,
EASILY,IRREGULAR,NEGOCIATION,PRESCRIPTION,RESPONSIBILITY,MEDICATION,EAGLE,CLASSMATE,VOLLEYBALL,COUNTABLE,
CHURCH,THURSDAY,CONSONANTS,SAILING,SIGHTSEEING,HOUSEHOLD CHORES,CLUMSY,FISHING,WORKPLACE,FESTIVAL,
STAND UP,CORRECTION,WORKPLACE,CAREFUL,NOVEMBER,EXCITEMENT,BOWLING,GEOGRAPHY,EXPLANATION,LOUDLY,
GARAGE,LIBRARY,FENCE,AFTERNOON,FRUITS,BORING,WHITE,SEA LION,OCTOPUS,JELLY FISH,
BROWN,PAINTINGS,ENTHUSIASTIC,SANDCASTLE,OFTEN,CLASSICAL,SATURDAY,CELEBRITY,MATERIAL,EXCUSE ME,
AMERICAN,DISHES,HAPPINESS,LAUNDROMAT,SKIRT,SNEAKERS,COLORS,ERASER,RAINFOREST,FLOOD,VOLCANO"""

words_list = [w.strip().lower() for w in words_raw.split(',')]

# Deduplicate preserving order
seen = set()
deduped = []
for w in words_list:
    if w not in seen:
        seen.add(w)
        deduped.append(w)

print(f"Final tournament word list: {len(deduped)} unique words")

# Update words.py
with open('words.py', 'r', encoding='utf-8') as f:
    content = f.read()

# Build the words block
quoted = [f'"{w}"' for w in deduped]
lines = []
for i in range(0, len(quoted), 6):
    chunk = quoted[i:i+6]
    lines.append('                ' + ', '.join(chunk) + ',')

words_block = '\n'.join(lines)

# Replace tournament config
import re
pattern = r'"tournament":\s*\{[^}]*"words":\s*\{[^}]*"easy":\s*\[(.*?)\],'
replacement = f'''"tournament": {{
        "label": "Tournament",
        "ranked_week": 1,
        "words": {{
            "easy": [
{words_block}
            ],'''

content = re.sub(pattern, replacement, content, flags=re.DOTALL)

with open('words.py', 'w', encoding='utf-8') as f:
    f.write(content)

print("Tournament list finalized and saved")
