# ==================== SPELLING BEE CONTEST WORDS ====================
# Difficulty is based on SPELLING DIFFICULTY (how likely users misspell/mistype),
# NOT word length. Each group has ~equal 1/3 split across easy/medium/hard.
# All groups use exactly 4 weeks.
# No word appears in more than one difficulty within the same group.

# ==================== GROUP 1 (244 words) ====================
# The user's exact word list, split into ~81/81/82 by spelling difficulty.
# Easy = common spelling, few tricky patterns
# Medium = moderately tricky (double letters, silent letters, common mistakes)
# Hard = very tricky spelling (unusual patterns, commonly misspelled, long complex words)

_GROUP1_EASY = [
    "accident", "address", "adventure", "agreement", "already",
    "ambitious", "ambulance", "animation", "applying", "attention",
    "authority", "autumn", "beautiful", "beginning", "believe",
    "biscuit", "business", "castle", "centre", "certainly",
    "challenge", "character", "chocolate", "confusing", "correctly",
    "dangerous", "decisions", "delicious", "desserts", "education",
    "equipment", "eternity", "excellent", "expensive", "features",
    "following", "foreign", "freezing", "furniture", "further",
    "geography", "grateful", "headache", "hopefully", "important",
    "interesting", "knowledge", "languages", "library", "lightning",
    "luggage", "marathon", "medication", "medicine", "minute",
    "monitoring", "necessary", "opposite", "paperless", "queue",
    "sentences", "stressful", "suggestions", "technology", "temperature",
    "terrifying", "thrilling", "throughout", "toothache", "vegetables",
    "vocabulary", "wednesday", "food court", "ice hockey", "bottle opener",
    "computer room", "movie theater", "shopping bag", "wooden spoon",
    "washing machine", "weekly planner",
]

_GROUP1_MEDIUM = [
    "accomplishments", "achievements", "acquiring", "administration",
    "advertisement", "aeroplane", "afterwards", "alcoholism", "apparently",
    "application", "appointment", "appreciation", "appropriate", "architecture",
    "arrangements", "association", "availability", "beautifully", "belongings",
    "businessman", "catastrophic", "championship", "cheesecake", "chemistry",
    "chinatown", "civilization", "colleagues", "combination", "comfortable",
    "commitment", "communication", "comparative", "competition", "completely",
    "conditions", "continuous", "corkscrew", "countryside", "definition",
    "descriptions", "dictionary", "difference", "disappointing", "distraction",
    "distribution", "documentary", "earthquake", "effectively", "employment",
    "encyclopedia", "engineering", "entertainment", "equality",
    "examination", "excitement", "exhibition", "experience", "exploration",
    "expression", "extremely", "facilities", "girlfriend", "harmonious",
    "headphones", "housewares", "imagination", "immediately", "immigration",
    "information", "international", "introducing", "investigation", "involving",
    "jewellery", "kilometre", "literature", "management", "modernization",
    "mountainous", "neighborhood", "phenomenon", "philosophy", "politician",
    "possessions", "predictions", "presentations", "questioning",
]

_GROUP1_HARD = [
    "acknowledgement", "admiration mark", "apprehensive", "astronomical",
    "bungee jumping", "chopping board", "circumstances", "comprehension",
    "comprehensive", "consciously", "consecutively", "consideration",
    "consolidation", "containing", "courageously", "dermatologist",
    "economically", "effectiveness", "enthusiastic", "extraordinary",
    "hard-working", "household chores", "hypertension", "hyperthyroidism",
    "hypervitaminosis", "independently", "indirectly", "internationally",
    "interruption", "kitesurfing", "knuckles", "linguistics",
    "mediterranean", "methodology", "microwave oven", "mischievous",
    "nevertheless", "overwhelming", "paragliding", "participles",
    "possibilities", "potentially", "prescription", "rainforest",
    "refrigerator", "relationship", "resolutions", "revolutionary",
    "ridiculous", "romanticism", "salesperson", "satisfaction",
    "scientifically", "screwdriver", "shopping center", "sightseeing",
    "significance", "skyscrapers", "snorkeling", "statements",
    "stomachache", "strawberry", "successfully", "surprisingly",
    "technician", "thematical", "transnational", "under pressure",
    "understandable", "understanding", "unforgettable", "united states",
    "university", "unstoppable", "windsurfing", "workaholic",
]

# ==================== GROUP 2 (200 words) ====================
# ~67/67/66 split
_GROUP2_EASY = [
    "accident", "address", "already", "applying", "autumn",
    "believe", "biscuit", "business", "castle", "centre",
    "desserts", "equality", "eternity", "features", "freezing",
    "further", "foreign", "grateful", "headache", "knuckles",
    "library", "luggage", "marathon", "medicine", "minute",
    "attention", "animation", "beginning", "challenge", "character",
    "certainly", "confusing", "correctly", "decisions", "delicious",
    "equipment", "excellent", "expensive", "following", "furniture",
    "geography", "hopefully", "important", "interesting", "knowledge",
    "languages", "lightning", "necessary", "paperless",
    "sentences", "stressful", "thrilling", "toothache", "vegetables",
]

_GROUP2_MEDIUM = [
    "acquiring", "aeroplane", "agreement", "ambitious", "ambulance",
    "apparently", "application", "appointment", "architecture",
    "arrangements", "association", "availability", "beautifully",
    "belongings", "businessman", "catastrophic", "championship",
    "cheesecake", "chemistry", "chinatown", "civilization", "colleagues",
    "combination", "comfortable", "commitment", "communication",
    "comparative", "competition", "completely", "conditions", "continuous",
    "corkscrew", "countryside", "definition", "dictionary", "difference",
    "disappointing", "distraction", "distribution", "documentary",
    "earthquake", "effectively", "employment", "encyclopedia",
    "entertainment", "enthusiastic", "examination", "excitement",
    "exhibition", "experience", "exploration", "expression", "extremely",
    "facilities", "girlfriend", "harmonious", "headphones", "housewares",
    "imagination", "immediately", "immigration", "information",
    "international", "introducing", "investigation", "involving",
    "jewellery", "kilometre",
]

_GROUP2_HARD = [
    "accomplishments", "achievements", "acknowledgement", "administration",
    "admiration mark", "advertisement", "afterwards", "alcoholism",
    "appreciation", "apprehensive", "appropriate", "astronomical",
    "bottle opener", "bungee jumping", "chopping board", "circumstances",
    "comprehension", "comprehensive", "computer room", "consciously",
    "consecutively", "consideration", "consolidation", "containing",
    "courageously", "dermatologist", "descriptions", "economically",
    "effectiveness", "engineering", "extraordinary", "food court",
    "hard-working", "household chores", "hypertension", "hyperthyroidism",
    "hypervitaminosis", "ice hockey", "independently", "indirectly",
    "internationally", "interruption", "kitesurfing", "linguistics",
    "literature", "management", "medication", "mediterranean",
    "methodology", "microwave oven", "mischievous", "modernization",
    "monitoring", "mountainous", "movie theater", "neighborhood",
    "nevertheless", "overwhelming", "paragliding", "phenomenon",
    "philosophy", "politician", "possessions", "possibilities",
    "potentially",
]

# ==================== GROUP 3 (240 words) ====================
# ~80/80/80 split
_GROUP3_EASY = [
    "applying", "creation", "desserts", "equality", "eternity",
    "features", "feelings", "freezing", "further", "grateful",
    "headache", "kindness", "knuckles", "luggage", "marathon",
    "messages", "musician", "speaking", "studying", "swimming",
    "weather", "address", "believe", "biscuit", "castle",
    "centre", "doctor", "family", "foreign", "minute",
    "acquiring", "adventure", "ambitious", "beginning", "breakfast",
    "butterfly", "challenge", "character", "childhood", "chinatown",
    "confusing", "corkscrew", "correctly", "dangerous", "education",
    "excellent", "expensive", "extremely", "following", "food court",
    "geography", "hopefully", "ice hockey", "important", "involving",
    "languages", "lightning", "paperless", "stressful", "thrilling",
    "animation", "attention", "authority", "agreement", "aeroplane",
    "chemistry", "continuous", "jewellery", "kilometre", "crocodile",
    "accident", "already", "chocolate", "furniture", "library",
    "beautiful", "sentences",
]

_GROUP3_MEDIUM = [
    "accomplishments", "achievements", "acknowledgement", "administration",
    "admiration mark", "alcoholism", "apparently", "application",
    "appointment", "appreciation", "apprehensive", "appropriate",
    "architecture", "arrangements", "association", "astronomical",
    "availability", "beautifully", "belongings", "bottle opener",
    "bungee jumping", "businessman", "catastrophic", "championship",
    "cheesecake", "chopping board", "circumstances", "civilization",
    "colleagues", "combination", "comfortable", "commitment",
    "communication", "comparative", "competition", "completely",
    "comprehension", "comprehensive", "computer room", "conditions",
    "consciously", "consecutively", "consideration", "consolidation",
    "containing", "countryside", "courageously", "decisions",
    "definition", "dermatologist", "descriptions", "dictionary",
    "difference", "disappointing", "distraction", "distribution",
    "documentary", "earthquake", "economically", "effectively",
    "effectiveness", "employment", "encyclopedia", "engineering",
    "entertainment", "enthusiastic", "equipment", "examination",
    "excitement", "exhibition", "experience", "exploration",
    "expression", "extraordinary", "facilities", "girlfriend",
    "harmonious", "headphones", "household chores", "housewares",
]

_GROUP3_HARD = [
    "hypertension", "hyperthyroidism", "hypervitaminosis", "imagination",
    "immediately", "immigration", "independently", "indirectly",
    "information", "interesting", "international", "internationally",
    "interruption", "introducing", "investigation", "kitesurfing",
    "linguistics", "literature", "management", "medication",
    "mediterranean", "methodology", "microwave oven", "mischievous",
    "modernization", "monitoring", "mountainous", "movie theater",
    "neighborhood", "nevertheless", "overwhelming", "paragliding",
    "participles", "phenomenon", "philosophy", "politician",
    "possessions", "possibilities", "potentially", "predictions",
    "prescription", "presentations", "questioning", "rainforest",
    "refrigerator", "relationship", "resilience", "resolutions",
    "revolutionary", "ridiculous", "romanticism", "salesperson",
    "satisfaction", "scientifically", "screwdriver", "shopping bag",
    "shopping center", "sightseeing", "significance", "skyscrapers",
    "snorkeling", "statements", "strawberry", "successfully",
    "suggestions", "surprisingly", "sustainability", "technician",
    "technology", "temperature", "terrifying", "thematical",
    "throughout", "transnational", "under pressure", "understandable",
    "understanding", "unforgettable", "united states", "university",
    "unstoppable", "vegetables", "vocabulary", "washing machine",
    "weekly planner", "windsurfing", "wooden spoon", "workaholic",
    "apartment", "birthday party", "chicken wings", "christmas tree",
    "decorations", "friendship", "grandparents", "hard-working",
]

# ==================== GROUP 4 (300 words) ====================
# ~100/100/100 split
_GROUP4_EASY = [
    "accuracy", "addition", "analysis", "argument", "adventure",
    "agreement", "alternate", "apartment", "attention", "available",
    "beautiful", "calculate", "celebrate", "celebrity", "committee",
    "community", "condition", "cooperate", "emergency", "emotional",
    "enjoyable", "entertain", "fortunate", "geography", "imaginary",
    "insurance", "intention", "knowledge", "memorable", "necessary",
    "territory", "understand", "appreciate", "beneficial", "capability",
    "centimeter", "collection", "combination", "comfortable", "commercial",
    "comparison", "competitor", "conference", "confidence", "connection",
    "considered", "continuous", "creativity", "decoration", "dedication",
    "definitely", "department", "determined", "difficulty", "discipline",
    "discovered", "discussion", "economical", "evaluation", "everlasting",
    "exaggerate", "experience", "expression", "federation", "generosity",
    "graduation", "harmonious", "hesitation", "impossible", "impression",
    "indication", "industrial", "innovation", "innovative", "instructor",
    "management", "meaningful", "motivation", "mysterious", "negotiable",
    "particular", "philosophy", "population",
    "possession", "precaution", "prediction", "preference", "production",
    "protection", "reflection", "regulatory", "reputation", "resolution",
    "revolution", "scientific", "separation", "simplicity", "technology",
]

_GROUP4_MEDIUM = [
    "accommodate", "approximate", "association", "calculation",
    "characterize", "collaborator", "communication", "compensation",
    "complication", "computerized", "concentration", "congratulate",
    "consideration", "consolidate", "construction", "constitution",
    "consumerism", "consumption", "contemplation", "continuation",
    "contradiction", "contribution", "conventional", "conversation",
    "cooperation", "correlation", "declaration", "deliberation",
    "demonstrate", "demonstration", "dependability", "determination",
    "development", "dictionaries", "directional", "disciplinary",
    "disadvantage", "disagreement", "disappearing", "discontinued",
    "discoverable", "discouragement", "discriminate", "disobedience",
    "educational", "effectiveness", "elimination", "embarrassment",
    "emphasizing", "encouragement", "encouraging", "endangered",
    "energetically", "engineering", "enjoyability", "enthusiasm",
    "environment", "equivalently", "especially",
    "establishment", "estimation", "examination", "exaggeration",
    "exasperation", "expectation", "experimental", "experimenting",
    "explanation", "explanatory", "exploitation", "extermination",
    "extraordinary", "fabrication", "facilitator", "fascinating",
    "fascination", "fortification", "frustrating", "frustration",
    "geometrical", "hesitatingly", "hospitality", "hospitalization",
    "imagination", "immediately", "improvement",
    "improvisation", "independence",
    "independent", "individually", "information", "informational",
    "influential", "inspiration", "inspirational", "installation",
    "instantaneous", "institutional", "instrumental", "intellectual",
]

_GROUP4_HARD = [
    "intelligent", "intentionality", "interesting", "interpretation",
    "interrelation", "interrogation", "intervention", "international",
    "interviewer", "introducing", "introduction", "investigation",
    "irresponsible", "irritating", "justification", "legitimately",
    "liberation", "literature", "magnificent", "magnification",
    "maintainable", "manufacturing", "marginalization", "mediterranean",
    "misunderstand", "modification", "multiplication", "multiplying",
    "negotiation", "operational", "opportunity", "organization",
    "organizational", "orientation", "outstanding", "overwhelming",
    "parliament", "participate", "participation", "perception",
    "performance", "perpetuation", "personality", "personification",
    "philosophical", "photography", "possibilities", "possibility",
    "practically", "precipitation", "predomination", "preparation",
    "presentation", "probability", "professional", "professorship",
    "programming", "progression", "pronunciation", "proportional",
    "questionable", "recognition", "recommendation", "reconstruction",
    "relationship", "reservation", "responsible", "revolutionary",
    "satisfaction", "sensational", "sensitization", "simultaneously",
    "sophisticated", "specifically", "specification", "spirituality",
    "statistical", "statistically", "stimulating", "supplementary",
    "surprisingly", "sustainability", "telecommunication", "temperature",
    "terminology", "theoretical", "traditionally", "translational",
    "transmission", "transparency", "transportation", "abbreviation",
    "accomplishment", "accessibility", "accommodation", "acknowledgement",
    "administration", "advertisement", "appropriation", "apprenticeship",
    "authoritative", "discrimination", "environmental", "experimentation",
    "identification", "implementation", "industrialization", "infrastructure",
    "internationalization", "miscommunication", "personalization", "professionalism",
]

# ==================== TOURNAMENT (200 words) ====================
# ~67/67/66 split
_TOURNAMENT_EASY = [
    "address", "balloon", "bathroom", "bedroom", "boring", "bowling",
    "castle", "children", "church", "climbing", "clumsy", "colors",
    "cupboard", "cycling", "daughter", "dishes", "dolphin", "eagle",
    "easily", "factory", "february", "fence", "fishing", "flood",
    "fruits", "handles", "jacket", "jungle", "keyboard", "library",
    "loudly", "monkey", "museum", "noodles", "often", "pharmacy",
    "property", "quickly", "rainbow", "sailing", "scissors", "shopping",
    "shoulder", "skirt", "sneakers", "speaking", "sweater", "swimming",
    "thailand", "theater", "thursday", "tiring", "waitress", "warming",
    "warning", "weather", "whistle", "afternoon", "airplane", "amazing",
    "badminton", "careful", "classical", "classmate", "correction",
    "countable", "countryside", "disgusting",
]

_TOURNAMENT_MEDIUM = [
    "consonants", "dining room", "earphones", "elephant", "engineer",
    "eraser", "evening", "festival", "garage", "grandchildren",
    "granddaughter", "grandfather", "groceries", "guinea pig",
    "hairbrush", "hairdresser", "happiness", "holidays", "homework",
    "instrument", "jelly fish", "laundromat", "lifestyle", "lunchtime",
    "material", "mountains", "necklace", "neighborhood", "newspaper",
    "notebook", "november", "octopus", "paintings", "prescription",
    "principal", "psychology", "questions", "rainforest", "remember",
    "sandcastle", "saturday", "scientist", "sightseeing", "american",
    "apostrophe", "businessman", "electrician", "enthusiastic",
    "everywhere", "excitement", "exercise", "expensive", "explanation",
    "fascinating", "fashionable", "furniture", "information",
    "interesting", "introducing", "irregular", "laboratory", "magazine",
    "medication", "medicine", "nationality", "negotiation",
    "opposite", "recognize",
]

_TOURNAMENT_HARD = [
    "bubble speech", "dislike", "down town", "green point", "images",
    "sea lion", "stand up", "white", "brown",
    "excuse me", "fire fighter", "household chores", "microwave oven",
    "movie theater", "office building", "police officer", "post office",
    "refrigerator", "responsibility", "sales assistant", "saxophone",
    "skateboarding", "snowboarding", "statements", "steering wheel",
    "strawberry", "supermarket", "surprising", "television",
    "thirty three", "tomatoes", "tomorrow", "toothbrush",
    "train station", "umbrella", "uncountable", "understand",
    "united kingdom", "vegetables", "videogames", "volcano",
    "volleyball", "waking up", "wheelchair", "workplace",
    "accommodation", "accomplishment", "advertisement", "announcement",
    "anticipation", "apprenticeship", "appropriation", "authoritative",
    "discrimination", "environmental", "experimentation", "identification",
    "implementation", "infrastructure", "miscommunication",
    "personalization", "professionalism", "telecommunication",
    "transportation", "vulnerability",
]


# ==================== BACKWARD COMPAT GLOBALS ====================
# Group1 is the "default" group used by global references
EASY_WORDS = _GROUP1_EASY
MEDIUM_WORDS = _GROUP1_MEDIUM
HARD_WORDS = _GROUP1_HARD
LONG_HARD_WORDS = _GROUP1_HARD  # alias

# Multi-word phrases for Group1
PHRASE_WORDS = [
    "food court", "ice hockey", "computer room", "movie theater",
    "shopping bag", "shopping center", "bottle opener", "bungee jumping",
    "chopping board", "microwave oven", "household chores", "united states",
    "washing machine", "weekly planner", "wooden spoon", "admiration mark",
    "under pressure",
]


# ==================== WORD_IMAGES (emojis for ALL words in ALL groups) ====================
WORD_IMAGES = {
    # --- Common across groups ---
    "accident": "🚗", "accomplishments": "🏆", "achievements": "🥇",
    "acknowledge": "✅", "acknowledgement": "🙏", "acquiring": "🎯",
    "address": "📬", "administration": "🏢", "admiration mark": "❗",
    "adventure": "🗺️", "advertisement": "📺", "aeroplane": "✈️",
    "afterwards": "⏩", "agreement": "🤝", "alcoholism": "🍺",
    "already": "⏰", "ambitious": "🚀", "ambulance": "🚑",
    "animation": "🎬", "apparently": "🧐", "application": "📱",
    "applying": "📋", "appointment": "📅", "appreciation": "💝",
    "apprehensive": "😟", "appropriate": "✅", "architecture": "🏗️",
    "arrangements": "📋", "association": "🤝", "astronomical": "🔭",
    "attention": "👀", "authority": "👮", "autumn": "🍂",
    "availability": "📆", "beautiful": "🌸", "beautifully": "🌺",
    "beginning": "🌅", "believe": "🙏", "belongings": "🎒",
    "biscuit": "🍪", "bottle opener": "🍾", "bungee jumping": "🤸",
    "business": "💼", "businessman": "👔", "castle": "🏰",
    "catastrophic": "💥", "centre": "🏢", "certainly": "✅",
    "challenge": "💪", "championship": "🥇", "character": "🎭",
    "cheesecake": "🍰", "chemistry": "🧪", "chinatown": "🏮",
    "chocolate": "🍫", "chopping board": "🔪", "circumstances": "🔄",
    "civilization": "🏛️", "colleagues": "👥", "combination": "🔀",
    "comfortable": "😌", "commitment": "💍", "communication": "📞",
    "comparative": "⚖️", "competition": "🏅", "completely": "💯",
    "comprehension": "🧠", "comprehensive": "📚", "computer room": "🖥️",
    "conditions": "📋", "confusing": "😵", "consciously": "🧘",
    "consecutively": "🔢", "consideration": "🤔", "consolidation": "🔗",
    "containing": "📦", "continuous": "♾️", "corkscrew": "🍷",
    "correctly": "✔️", "countryside": "🌾", "courageously": "🦁",
    "creation": "🎨", "dangerous": "⚠️", "decisions": "🤔",
    "definition": "📖", "delicious": "😋", "dermatologist": "👨‍⚕️",
    "descriptions": "📝", "desserts": "🍰", "dictionary": "📖",
    "difference": "🔄", "disappointing": "😞", "discipline": "📏",
    "distraction": "📱", "distribution": "📦", "documentary": "🎥",
    "earthquake": "🌋", "economically": "💰", "education": "🎓",
    "effectively": "📈", "effectiveness": "📈", "employment": "💼",
    "encyclopedia": "📖", "engineering": "⚙️", "entertainment": "🎭",
    "enthusiastic": "🤩", "equality": "⚖️", "equipment": "🔧",
    "eternity": "♾️", "examination": "📝", "excellent": "🏅",
    "excitement": "🎉", "exhibition": "🖼️", "expensive": "💎",
    "experience": "🌟", "exploration": "🧭", "expression": "😊",
    "extraordinary": "✨", "extremely": "🔥", "facilities": "🏗️",
    "features": "⭐", "feelings": "💕", "following": "👣",
    "food court": "🍔", "foreign": "🌍", "freezing": "🥶",
    "friendship": "🤝", "furniture": "🛋️", "further": "➡️",
    "geography": "🌍", "girlfriend": "💑", "grateful": "🤗",
    "hard-working": "💪", "hardworking": "💪", "harmonious": "🎶",
    "headache": "🤕", "headphones": "🎧", "hopefully": "🤞",
    "household chores": "🧹", "housewares": "🏠", "hypertension": "❤️",
    "hyperthyroidism": "🏥", "hypervitaminosis": "💊",
    "ice hockey": "🏒", "imagination": "💭", "immediately": "⏰",
    "immigration": "🛂", "important": "❗", "independently": "🦅",
    "indirectly": "↩️", "information": "ℹ️", "interesting": "🤩",
    "international": "🌐", "internationally": "🌐", "interruption": "🛑",
    "introducing": "🎤", "investigation": "🔍", "involving": "🔗",
    "jewellery": "💎", "kilometre": "📏", "kindness": "💗",
    "kitesurfing": "🪁", "knowledge": "🧠", "knuckles": "✊",
    "languages": "🗣️", "library": "📚", "lightning": "⚡",
    "linguistics": "🗣️", "literature": "📚", "luggage": "🧳",
    "management": "📊", "marathon": "🏃", "medication": "💊",
    "medicine": "💊", "mediterranean": "🌊", "messages": "💬",
    "methodology": "📐", "microwave oven": "📡", "mischievous": "😈",
    "minute": "⏱️", "modernization": "🏙️", "monitoring": "📡",
    "mountainous": "⛰️", "movie theater": "🎬", "musician": "🎵",
    "necessary": "📌", "neighborhood": "🏘️", "nevertheless": "🔄",
    "opposite": "↔️", "overwhelming": "🌊", "paperless": "♻️",
    "paragliding": "🪂", "participles": "📝", "phenomenon": "🌠",
    "philosophy": "🤔", "politician": "🏛️", "possessions": "🏠",
    "possibilities": "🌈", "potentially": "🔮", "predictions": "🔮",
    "prescription": "💊", "presentations": "📊", "questioning": "❓",
    "queue": "🚶‍♂️", "rainforest": "🌴", "refrigerator": "🧊",
    "relationship": "💑", "resilience": "💪", "resolutions": "🎯",
    "revolutionary": "✊", "ridiculous": "🤣", "romanticism": "💕",
    "salesperson": "🛒", "satisfaction": "😊", "scientifically": "🔬",
    "screwdriver": "🪛", "sentences": "📝", "shopping bag": "🛍️",
    "shopping center": "🏬", "sightseeing": "📸", "significance": "⭐",
    "skyscrapers": "🏙️", "snorkeling": "🤿", "speaking": "🗣️",
    "statements": "📄", "stomachache": "🤢", "strawberry": "🍓",
    "stressful": "😰", "studying": "📖", "successfully": "🎉",
    "suggestions": "💡", "surprisingly": "😲", "sustainability": "🌱",
    "swimming": "🏊", "technician": "🔧", "technology": "💻",
    "temperature": "🌡️", "terrifying": "😱", "thematical": "📋",
    "thrilling": "🎢", "throughout": "🔄", "toothache": "🦷",
    "transnational": "🌍", "under pressure": "😤",
    "understandable": "💡", "understanding": "🤝", "unforgettable": "💫",
    "united states": "🇺🇸", "university": "🎓", "unstoppable": "🚀",
    "vegetables": "🥦", "vocabulary": "📖", "washing machine": "🧺",
    "weather": "🌤️", "wednesday": "📅", "weekly planner": "📅",
    "windsurfing": "🏄", "wooden spoon": "🥄", "workaholic": "⏰",
    # --- Group 3 unique ---
    "breakfast": "🥞", "butterfly": "🦋", "childhood": "👶",
    "crocodile": "🐊", "apartment": "🏢", "birthday party": "🎂",
    "chicken wings": "🍗", "christmas tree": "🎄", "decorations": "🎀",
    "grandparents": "👴", "doctor": "👨‍⚕️", "family": "👨‍👩‍👧‍👦",
    # --- Group 4 unique ---
    "accuracy": "🎯", "addition": "➕", "analysis": "📊",
    "argument": "💬", "alternate": "🔄", "apartment": "🏢",
    "available": "✅", "calculate": "🔢", "celebrate": "🎉",
    "celebrity": "⭐", "committee": "🏛️", "community": "🏘️",
    "condition": "📋", "cooperate": "🤝", "emergency": "🚨",
    "emotional": "😢", "enjoyable": "😊", "entertain": "🎪",
    "fortunate": "🍀", "imaginary": "🦄", "insurance": "🛡️",
    "intention": "🎯", "memorable": "📸", "territory": "🗺️",
    "understand": "🧠", "appreciate": "💝", "beneficial": "✅",
    "capability": "💪", "centimeter": "📏", "collection": "📦",
    "commercial": "📺", "comparison": "⚖️", "competitor": "🏅",
    "conference": "🏢", "confidence": "💪", "connection": "🔗",
    "considered": "🤔", "creativity": "🎨", "decoration": "🎀",
    "dedication": "💎", "definitely": "💯", "department": "🏢",
    "determined": "💪", "difficulty": "📈", "discovered": "🔍",
    "discussion": "💬", "economical": "💰", "evaluation": "📊",
    "everlasting": "♾️", "exaggerate": "📢", "federation": "🏛️",
    "generosity": "🎁", "graduation": "🎓", "hesitation": "🤔",
    "impossible": "🚫", "impression": "💭", "indication": "👉",
    "industrial": "🏭", "innovation": "💡", "innovative": "💡",
    "instructor": "👩‍🏫", "meaningful": "❤️", "motivation": "🔥",
    "mysterious": "🔮", "negotiable": "🤝", "particular": "📌",
    "perception": "👁️", "permission": "✅", "population": "👥",
    "possession": "🏠", "precaution": "⚠️", "prediction": "🔮",
    "preference": "⭐", "production": "🏭", "protection": "🛡️",
    "reflection": "🪞", "regulatory": "📋", "reputation": "⭐",
    "resolution": "🎯", "revolution": "✊", "scientific": "🔬",
    "separation": "✂️", "simplicity": "✨", "accommodate": "🏨",
    "approximate": "📏", "calculation": "🔢", "characterize": "📋",
    "collaborator": "🤝", "compensation": "💰", "complication": "🔄",
    "computerized": "💻", "concentration": "🧘", "congratulate": "🎉",
    "consolidate": "🔗", "construction": "🏗️", "constitution": "📜",
    "consumerism": "🛒", "consumption": "📊", "contemplation": "🤔",
    "continuation": "➡️", "contradiction": "🔄", "contribution": "🎁",
    "conventional": "📋", "conversation": "💬", "cooperation": "🤝",
    "correlation": "📊", "declaration": "📜", "deliberation": "🤔",
    "demonstrate": "👉", "demonstration": "📊", "dependability": "💪",
    "determination": "💪", "development": "📈", "dictionaries": "📖",
    "directional": "🧭", "disciplinary": "⚖️", "disadvantage": "👎",
    "disagreement": "😤", "disappearing": "🫥", "discontinued": "🚫",
    "discoverable": "🔍", "discouragement": "😞", "discriminate": "⚖️",
    "disobedience": "🚫", "educational": "🎓", "elimination": "❌",
    "embarrassment": "😳", "emphasizing": "❗", "encouragement": "💪",
    "encouraging": "👍", "endangered": "🦏", "energetically": "⚡",
    "enjoyability": "😊", "enthusiasm": "🤩", "environment": "🌿",
    "environmental": "🌿", "equivalently": "⚖️", "especially": "⭐",
    "establishment": "🏢", "estimation": "📊", "exaggeration": "📢",
    "exasperation": "😤", "expectation": "🤞", "experimental": "🔬",
    "experimenting": "🧪", "explanation": "💡", "explanatory": "📖",
    "exploitation": "⚠️", "extermination": "☠️", "fabrication": "🏭",
    "facilitator": "🤝", "fascinating": "🤩", "fascination": "✨",
    "fortification": "🏰", "frustrating": "😤", "frustration": "😤",
    "geometrical": "📐", "hesitatingly": "🤔", "hospitality": "🏨",
    "hospitalization": "🏥", "identification": "🪪",
    "implementation": "⚙️", "improvement": "📈", "improvisation": "🎭",
    "independence": "🦅", "independent": "🦅", "individually": "👤",
    "informational": "ℹ️", "influential": "👑", "inspiration": "💡",
    "inspirational": "✨", "installation": "⚙️", "instantaneous": "⚡",
    "institutional": "🏛️", "instrumental": "🎵", "intellectual": "🧠",
    "intelligent": "🧠", "intentionality": "🎯", "interpretation": "🔍",
    "interrelation": "🔗", "interrogation": "❓", "intervention": "🤝",
    "interviewer": "🎤", "introduction": "👋", "irresponsible": "🚫",
    "irritating": "😤", "justification": "⚖️", "legitimately": "✅",
    "liberation": "🕊️", "magnificent": "✨", "magnification": "🔍",
    "maintainable": "🔧", "manufacturing": "🏭", "marginalization": "⚠️",
    "misunderstand": "😵", "modification": "🔧", "multiplication": "✖️",
    "multiplying": "✖️", "negotiation": "🤝", "operational": "⚙️",
    "opportunity": "🚪", "organization": "📋", "organizational": "📋",
    "orientation": "🧭", "outstanding": "⭐", "parliament": "🏛️",
    "participate": "🤝", "participation": "🤝", "performance": "🎭",
    "perpetuation": "♾️", "personality": "🧠", "personification": "🎭",
    "philosophical": "🤔", "photography": "📸", "possibility": "🌈",
    "practically": "⚙️", "precipitation": "🌧️", "predomination": "👑",
    "preparation": "📋", "presentation": "📊", "probability": "📊",
    "professional": "👔", "professorship": "🎓", "programming": "💻",
    "progression": "📈", "pronunciation": "🗣️", "proportional": "⚖️",
    "questionable": "❓", "recognition": "🏅", "recommendation": "👍",
    "reconstruction": "🔧", "reservation": "📋", "responsible": "✅",
    "sensational": "✨", "sensitization": "🧘", "simultaneously": "⏱️",
    "sophisticated": "🎩", "specifically": "🎯", "specification": "📋",
    "spirituality": "🧘", "statistical": "📊", "statistically": "📊",
    "stimulating": "⚡", "supplementary": "📎", "telecommunication": "📡",
    "terminology": "📖", "theoretical": "💭", "traditionally": "🏛️",
    "translational": "🌐", "transmission": "📡", "transparency": "🔍",
    "transportation": "🚌", "abbreviation": "📝", "accomplishment": "🏆",
    "accessibility": "♿", "accommodation": "🏨", "appropriation": "⚖️",
    "apprenticeship": "🎓", "authoritative": "👮", "discrimination": "⚖️",
    "experimentation": "🧪", "industrialization": "🏭",
    "infrastructure": "🏗️", "internationalization": "🌐",
    "miscommunication": "😵", "personalization": "🎯",
    "professionalism": "👔",
    # --- Tournament unique ---
    "balloon": "🎈", "bathroom": "🚿", "bedroom": "🛏️", "boring": "😴",
    "bowling": "🎳", "children": "👧", "church": "⛪", "climbing": "🧗",
    "clumsy": "🤕", "colors": "🎨", "cupboard": "🗄️", "cycling": "🚴",
    "daughter": "👧", "dishes": "🍽️", "dolphin": "🐬", "eagle": "🦅",
    "easily": "✅", "factory": "🏭", "february": "📅", "fence": "🏡",
    "fishing": "🎣", "flood": "🌊", "fruits": "🍎", "handles": "🚪",
    "jacket": "🧥", "jungle": "🌴", "keyboard": "⌨️", "loudly": "📢",
    "monkey": "🐒", "museum": "🏛️", "noodles": "🍜", "often": "🔁",
    "pharmacy": "💊", "property": "🏠", "quickly": "⚡", "rainbow": "🌈",
    "sailing": "⛵", "scissors": "✂️", "shopping": "🛒", "shoulder": "💪",
    "skirt": "👗", "sneakers": "👟", "sweater": "🧥", "thailand": "🇹🇭",
    "theater": "🎭", "thursday": "📅", "tiring": "😴", "waitress": "🍽️",
    "warming": "🌡️", "warning": "⚠️", "whistle": "📯", "afternoon": "🌅",
    "airplane": "✈️", "amazing": "🤩", "badminton": "🏸", "careful": "⚠️",
    "classical": "🎼", "classmate": "👥", "correction": "✏️",
    "countable": "🔢", "disgusting": "🤮", "consonants": "🔤",
    "dining room": "🍽️", "earphones": "🎧", "elephant": "🐘",
    "engineer": "⚙️", "eraser": "🧹", "evening": "🌙", "festival": "🎪",
    "garage": "🚗", "grandchildren": "👶", "granddaughter": "👧",
    "grandfather": "👴", "groceries": "🛒", "guinea pig": "🐹",
    "hairbrush": "💇", "hairdresser": "💇‍♀️", "happiness": "😊",
    "holidays": "🏖️", "homework": "📚", "instrument": "🎵",
    "jelly fish": "🪼", "laundromat": "🧺", "lifestyle": "🏃",
    "lunchtime": "🍴", "material": "📦", "mountains": "⛰️",
    "necklace": "📿", "newspaper": "📰", "notebook": "📓",
    "november": "📅", "octopus": "🐙", "paintings": "🖼️",
    "principal": "🏫", "psychology": "🧠", "questions": "❓",
    "remember": "🧠", "sandcastle": "🏖️", "saturday": "📅",
    "scientist": "🔬", "american": "🇺🇸", "apostrophe": "✏️",
    "electrician": "⚡", "everywhere": "🌍", "excuse me": "🙏",
    "exercise": "🏋️", "explanation": "💡", "fashionable": "👗",
    "fire fighter": "🚒", "irregular": "🔀", "laboratory": "🧪",
    "magazine": "📰", "nationality": "🌍", "office building": "🏢",
    "police officer": "👮", "post office": "📮", "recognize": "🔍",
    "responsibility": "📋", "sales assistant": "🛒", "saxophone": "🎷",
    "skateboarding": "🛹", "snowboarding": "🏂", "steering wheel": "🚗",
    "supermarket": "🛒", "surprising": "😲", "television": "📺",
    "thirty three": "3️⃣", "tomatoes": "🍅", "tomorrow": "📆",
    "toothbrush": "🪥", "train station": "🚂", "umbrella": "☂️",
    "uncountable": "♾️", "united kingdom": "🇬🇧", "videogames": "🎮",
    "volcano": "🌋", "volleyball": "🏐", "waking up": "⏰",
    "wheelchair": "♿", "workplace": "🏢", "bubble speech": "💬",
    "dislike": "👎", "down town": "🏙️", "green point": "🟢",
    "images": "🖼️", "sea lion": "🦭", "stand up": "🧍", "white": "⬜",
    "brown": "🟤", "vulnerability": "💔",
    "anticipation": "🤞",
    "airport": "✈️", "announcement": "📢", "camping": "⛺",
}


# ==================== WORD_SENTENCES ====================
WORD_SENTENCES = {
    "accident": "There was a car accident on the highway.",
    "accomplishments": "Her accomplishments in science are impressive.",
    "achievements": "The school celebrated the students' achievements.",
    "acknowledge": "Please acknowledge that you received the email.",
    "acknowledgement": "He received an acknowledgement for his hard work.",
    "acquiring": "She is acquiring new skills every day.",
    "address": "Can you give me your home address?",
    "administration": "The school administration organized the event.",
    "admiration mark": "An admiration mark shows strong feeling.",
    "adventure": "Going to the jungle was a real adventure.",
    "advertisement": "I saw an advertisement for the new phone.",
    "aeroplane": "The aeroplane flew over the mountains.",
    "afterwards": "We had lunch and went shopping afterwards.",
    "agreement": "They signed an agreement to work together.",
    "alcoholism": "Alcoholism is a serious health problem.",
    "already": "I have already finished my homework.",
    "ambitious": "She is very ambitious and works hard every day.",
    "ambulance": "Call an ambulance if someone is hurt.",
    "animation": "The animation in that movie was incredible.",
    "apparently": "Apparently, the store closes early on Sundays.",
    "application": "I submitted my application for the scholarship.",
    "applying": "He is applying for a job at the hospital.",
    "appointment": "I have a dentist appointment at three o'clock.",
    "appreciation": "She showed her appreciation with a thank-you card.",
    "apprehensive": "He felt apprehensive before the big exam.",
    "appropriate": "Please wear appropriate clothing for the ceremony.",
    "architecture": "The architecture of the building is stunning.",
    "arrangements": "We made arrangements for the school trip.",
    "association": "She joined the student association at school.",
    "astronomical": "The cost of the project was astronomical.",
    "attention": "Please pay attention to the teacher.",
    "authority": "The police have the authority to enforce the law.",
    "autumn": "The leaves change color in autumn.",
    "availability": "Please check the availability of the room.",
    "beautiful": "What a beautiful sunset over the ocean!",
    "beautifully": "She sings beautifully in the school choir.",
    "beginning": "The beginning of the story was very exciting.",
    "believe": "I believe you can do anything you set your mind to.",
    "belongings": "Keep your belongings safe while traveling.",
    "biscuit": "Would you like a biscuit with your tea?",
    "bottle opener": "Do you have a bottle opener I can borrow?",
    "bungee jumping": "Bungee jumping from the bridge was terrifying!",
    "business": "My uncle started his own business last year.",
    "businessman": "The businessman traveled to many countries.",
    "castle": "The old castle sits on top of the hill.",
    "catastrophic": "The earthquake had catastrophic effects on the city.",
    "centre": "The shopping centre is in the middle of town.",
    "certainly": "I will certainly be there on time.",
    "challenge": "Learning a new language is a big challenge.",
    "championship": "Our team won the championship this year!",
    "character": "The main character in the book is very brave.",
    "cheesecake": "My favorite dessert is strawberry cheesecake.",
    "chemistry": "We learned about chemical reactions in chemistry class.",
    "chinatown": "We had dinner in Chinatown last night.",
    "chocolate": "I love eating chocolate after dinner.",
    "chopping board": "Use the chopping board when cutting vegetables.",
    "circumstances": "Under the circumstances, we did our best.",
    "civilization": "Ancient civilization left behind many ruins.",
    "colleagues": "She gets along well with her colleagues at work.",
    "combination": "The combination of colors looks amazing.",
    "comfortable": "This sofa is very comfortable to sit on.",
    "commitment": "Success requires hard work and commitment.",
    "communication": "Good communication is important in teamwork.",
    "comparative": "We studied comparative adjectives in English class.",
    "competition": "The spelling competition was very exciting.",
    "completely": "I completely forgot about the meeting.",
    "comprehension": "Reading comprehension is tested on the exam.",
    "comprehensive": "The report was very comprehensive and detailed.",
    "computer room": "The students went to the computer room for class.",
    "conditions": "The weather conditions were perfect for a picnic.",
    "confusing": "The instructions were very confusing.",
    "consciously": "She consciously decided to eat healthier.",
    "consecutively": "He won the award three years consecutively.",
    "consideration": "Thank you for your consideration of my request.",
    "consolidation": "The consolidation of the two companies was successful.",
    "containing": "She opened a box containing old photographs.",
    "continuous": "The rain was continuous throughout the day.",
    "corkscrew": "We need a corkscrew to open the bottle.",
    "correctly": "Make sure you spell every word correctly.",
    "countryside": "The countryside is peaceful and quiet.",
    "courageously": "The firefighter courageously entered the burning building.",
    "creation": "The creation of the painting took many months.",
    "dangerous": "Swimming in the river can be dangerous.",
    "decisions": "We all have to make important decisions in life.",
    "definition": "Look up the definition of the word in the dictionary.",
    "delicious": "The cake my grandmother made was delicious.",
    "dermatologist": "The dermatologist examined the rash on my arm.",
    "descriptions": "Write detailed descriptions of the characters.",
    "desserts": "We had ice cream and cake for desserts.",
    "dictionary": "Look up the meaning in the dictionary.",
    "difference": "Can you tell the difference between the two?",
    "disappointing": "The test results were very disappointing.",
    "discipline": "Discipline is important for success in school.",
    "distraction": "My phone is a big distraction when I study.",
    "distribution": "The distribution of food reached all the villages.",
    "documentary": "We watched a documentary about ocean life.",
    "earthquake": "The earthquake shook the buildings for thirty seconds.",
    "economically": "The country is growing economically.",
    "education": "Education is the key to a better future.",
    "effectively": "She communicated effectively with her team.",
    "effectiveness": "The effectiveness of the medicine was proven.",
    "employment": "He found employment at a local restaurant.",
    "encyclopedia": "I found the answer in the encyclopedia.",
    "engineering": "She wants to study engineering at university.",
    "entertainment": "There is plenty of entertainment at the festival.",
    "enthusiastic": "The students were enthusiastic about the field trip.",
    "equality": "Everyone deserves equality and respect.",
    "equipment": "The school bought new sports equipment.",
    "eternity": "It felt like an eternity waiting in line.",
    "examination": "The final examination is next Monday.",
    "excellent": "You did an excellent job on your project!",
    "excitement": "The children could not hide their excitement.",
    "exhibition": "We visited an art exhibition at the museum.",
    "expensive": "That watch is too expensive for me.",
    "experience": "Traveling gives you a lot of experience.",
    "exploration": "Space exploration has led to many discoveries.",
    "expression": "Her expression showed that she was happy.",
    "extraordinary": "She has an extraordinary talent for painting.",
    "extremely": "The weather today is extremely hot.",
    "facilities": "The hotel has excellent facilities for guests.",
    "features": "This phone has many useful features.",
    "feelings": "It is important to express your feelings.",
    "following": "Read the following instructions carefully.",
    "food court": "Let us meet at the food court for lunch.",
    "foreign": "She speaks three foreign languages.",
    "freezing": "It is freezing outside, so wear a warm coat.",
    "furniture": "We need new furniture for the living room.",
    "further": "We need to walk further to reach the lake.",
    "geography": "In geography class, we learned about volcanoes.",
    "girlfriend": "He gave his girlfriend flowers for her birthday.",
    "grateful": "I am grateful for all the help you gave me.",
    "hard-working": "She is a very hard-working student.",
    "harmonious": "The choir sang in a harmonious way.",
    "headache": "I have a terrible headache today.",
    "headphones": "I use headphones to listen to music.",
    "hopefully": "Hopefully, it will not rain tomorrow.",
    "household chores": "Everyone should help with household chores.",
    "housewares": "We bought new housewares for the kitchen.",
    "hypertension": "The doctor said he has hypertension.",
    "hyperthyroidism": "Hyperthyroidism affects the thyroid gland.",
    "hypervitaminosis": "Taking too many vitamins can cause hypervitaminosis.",
    "ice hockey": "Ice hockey is a very fast sport.",
    "imagination": "Use your imagination to write a creative story.",
    "immediately": "Please come to the office immediately.",
    "immigration": "Immigration rules vary from country to country.",
    "important": "It is important to study regularly.",
    "independently": "He learned to work independently at a young age.",
    "indirectly": "He indirectly told me he was not coming.",
    "information": "You can find more information on the website.",
    "interesting": "That documentary was really interesting.",
    "international": "The international conference was held in Geneva.",
    "internationally": "The brand is known internationally.",
    "interruption": "Please continue without interruption.",
    "introducing": "Allow me to start by introducing myself.",
    "investigation": "The police started an investigation into the crime.",
    "involving": "The project involving all students was a success.",
    "jewellery": "She wore beautiful jewellery to the party.",
    "kilometre": "The school is one kilometre from my house.",
    "kindness": "Acts of kindness make the world a better place.",
    "kitesurfing": "Kitesurfing is an exciting water sport.",
    "knowledge": "Reading books increases your knowledge.",
    "knuckles": "He cracked his knuckles before the game.",
    "languages": "How many languages can you speak?",
    "library": "I borrowed three books from the library.",
    "lightning": "The lightning lit up the entire sky.",
    "linguistics": "Linguistics is the study of language.",
    "literature": "We are studying English literature this semester.",
    "luggage": "Do not forget to collect your luggage at the airport.",
    "management": "Good management is key to a successful business.",
    "marathon": "She trained for months to run the marathon.",
    "medication": "Remember to take your medication every morning.",
    "medicine": "Take your medicine after breakfast.",
    "mediterranean": "We sailed across the Mediterranean Sea.",
    "messages": "Please check your messages.",
    "methodology": "The research methodology was carefully designed.",
    "microwave oven": "Heat the soup in the microwave oven.",
    "minute": "Please wait one minute while I finish.",
    "mischievous": "The mischievous puppy chewed up the shoes.",
    "modernization": "The modernization of the city took many years.",
    "monitoring": "The nurse is monitoring the patient closely.",
    "mountainous": "The mountainous region is popular with hikers.",
    "movie theater": "We watched the new film at the movie theater.",
    "musician": "The musician performed a beautiful song.",
    "necessary": "It is necessary to study before the exam.",
    "neighborhood": "Our neighborhood is very friendly and safe.",
    "nevertheless": "It was raining; nevertheless, we went for a walk.",
    "opposite": "The bank is on the opposite side of the street.",
    "overwhelming": "The support from the community was overwhelming.",
    "paperless": "Our school is trying to go paperless.",
    "paragliding": "Paragliding over the valley was breathtaking.",
    "participles": "We learned about past and present participles.",
    "phenomenon": "The northern lights are a natural phenomenon.",
    "philosophy": "She studied philosophy at the university.",
    "politician": "The politician gave a speech about education.",
    "possessions": "He lost all his possessions in the fire.",
    "possibilities": "There are endless possibilities for the future.",
    "potentially": "This could potentially be the best solution.",
    "predictions": "The weather predictions say it will snow.",
    "prescription": "The doctor wrote a prescription for the medicine.",
    "presentations": "The students gave excellent presentations today.",
    "questioning": "The detective spent hours questioning the suspect.",
    "queue": "Please wait in the queue until it is your turn.",
    "rainforest": "The Amazon rainforest is home to many animals.",
    "refrigerator": "Put the milk back in the refrigerator.",
    "relationship": "A good relationship is built on trust.",
    "resilience": "She showed great resilience after the setback.",
    "resolutions": "She made New Year resolutions to exercise more.",
    "revolutionary": "The invention was truly revolutionary.",
    "ridiculous": "That idea sounds completely ridiculous!",
    "romanticism": "Romanticism was an important art movement.",
    "salesperson": "The salesperson helped us find the right size.",
    "satisfaction": "Finishing the puzzle gave me great satisfaction.",
    "scientifically": "The theory was scientifically proven.",
    "screwdriver": "I need a screwdriver to fix this shelf.",
    "sentences": "Write five sentences about your weekend.",
    "shopping bag": "She carried a heavy shopping bag home.",
    "shopping center": "The shopping center has over a hundred stores.",
    "sightseeing": "We spent the day sightseeing in Paris.",
    "significance": "The discovery had great significance for science.",
    "skyscrapers": "The city is full of tall skyscrapers.",
    "snorkeling": "We went snorkeling and saw colorful fish.",
    "speaking": "Public speaking can be challenging.",
    "statements": "The witness gave several statements to the police.",
    "stomachache": "I got a stomachache from eating too much candy.",
    "strawberry": "Strawberry is my favorite flavor of ice cream.",
    "stressful": "Moving to a new city can be stressful.",
    "studying": "He spends hours studying for his exams.",
    "successfully": "She successfully completed the marathon.",
    "suggestions": "Do you have any suggestions for the project?",
    "surprisingly": "Surprisingly, the test was easier than expected.",
    "sustainability": "Sustainability is key to protecting the environment.",
    "swimming": "We went swimming at the pool this morning.",
    "technician": "The technician fixed our computer quickly.",
    "technology": "Technology has changed the way we communicate.",
    "temperature": "The temperature dropped below zero last night.",
    "terrifying": "The horror movie was absolutely terrifying.",
    "thematical": "The exhibition was organized in a thematical way.",
    "thrilling": "The roller coaster ride was thrilling!",
    "throughout": "It rained throughout the entire day.",
    "toothache": "I went to the dentist because of a toothache.",
    "transnational": "The transnational company operates in many countries.",
    "under pressure": "She performs well even under pressure.",
    "understandable": "Your frustration is completely understandable.",
    "understanding": "Thank you for your understanding and patience.",
    "unforgettable": "The trip to Japan was an unforgettable experience.",
    "united states": "The United States is a large country.",
    "university": "She wants to study medicine at the university.",
    "unstoppable": "Once she starts, she is unstoppable!",
    "vegetables": "Eating vegetables is good for your health.",
    "vocabulary": "Reading helps you improve your vocabulary.",
    "washing machine": "The washing machine is broken again.",
    "weather": "The weather today is perfect for a picnic.",
    "wednesday": "We have a test on Wednesday.",
    "weekly planner": "I use a weekly planner to organize my tasks.",
    "windsurfing": "We tried windsurfing at the beach.",
    "wooden spoon": "Stir the sauce with a wooden spoon.",
    "workaholic": "My dad is a workaholic who never stops working.",
    # Group 3 extras
    "breakfast": "I had cereal and toast for breakfast.",
    "butterfly": "A beautiful butterfly landed on the flower.",
    "childhood": "My childhood was full of happy memories.",
    "crocodile": "We saw a crocodile at the zoo.",
    "apartment": "They moved into a new apartment downtown.",
    "birthday party": "We organized a birthday party for our friend.",
    "chicken wings": "We ordered chicken wings at the restaurant.",
    "christmas tree": "We decorated the christmas tree with ornaments.",
    "decorations": "The decorations made the room look beautiful.",
    "grandparents": "I visit my grandparents every weekend.",
    "doctor": "The doctor said I need to rest for a few days.",
    "family": "My family goes to the park every weekend.",
    "friendship": "Friendship is one of the most valuable things.",
    # --- Group 4 + Tournament sentences ---
    "abbreviation": "An abbreviation is a shortened form of a word.",
    "accessibility": "The building was designed with accessibility in mind.",
    "accommodate": "The hotel can accommodate up to three hundred guests.",
    "accommodation": "We booked accommodation near the beach.",
    "accomplishment": "Graduating from university was a great accomplishment.",
    "accuracy": "Accuracy is very important when doing math problems.",
    "addition": "In addition to English, she speaks French and Spanish.",
    "afternoon": "We have a meeting this afternoon at three.",
    "airplane": "The airplane landed safely at the airport.",
    "alternate": "We need to find an alternate route to school.",
    "amazing": "The magic show was absolutely amazing!",
    "american": "She studied American history at university.",
    "analysis": "The scientist did a careful analysis of the data.",
    "announcement": "The principal made an important announcement today.",
    "anticipation": "The children waited with anticipation for the holiday.",
    "apostrophe": "Do not forget to use an apostrophe in contractions.",
    "appreciate": "I really appreciate your help with this project.",
    "apprenticeship": "He completed an apprenticeship with a master carpenter.",
    "appropriation": "The appropriation of funds was approved by the committee.",
    "approximate": "Can you give me an approximate time of arrival?",
    "argument": "They had a friendly argument about the best movie.",
    "authoritative": "The teacher spoke in an authoritative voice.",
    "available": "Is this seat available or is someone sitting here?",
    "badminton": "We played badminton in the garden after lunch.",
    "balloon": "The red balloon floated up into the sky.",
    "bathroom": "Please wash your hands in the bathroom.",
    "bedroom": "She decorated her bedroom with colorful posters.",
    "beneficial": "Exercise is beneficial for your health.",
    "boring": "The long lecture was very boring.",
    "bowling": "We went bowling with friends on Saturday night.",
    "brown": "The dog has a shiny brown coat.",
    "bubble speech": "The comic used a bubble speech to show dialogue.",
    "calculate": "Use the formula to calculate the area of the circle.",
    "calculation": "The calculation was more difficult than expected.",
    "capability": "She has the capability to lead the entire team.",
    "careful": "Be careful when crossing the busy road.",
    "celebrate": "We will celebrate her birthday with a big party.",
    "celebrity": "The celebrity signed autographs for the fans.",
    "centimeter": "The insect was only one centimeter long.",
    "characterize": "Bright colors characterize his style of painting.",
    "children": "The children played happily in the park.",
    "church": "The old church has beautiful stained glass windows.",
    "classical": "She enjoys listening to classical music.",
    "classmate": "My classmate helped me with the homework.",
    "climbing": "Rock climbing is an exciting outdoor activity.",
    "clumsy": "He is a bit clumsy and often drops things.",
    "collaborator": "She worked with a collaborator on the research paper.",
    "collection": "He has an impressive collection of stamps.",
    "colors": "The rainbow displayed many beautiful colors.",
    "commercial": "The commercial break lasted about five minutes.",
    "committee": "The committee met to discuss the new school rules.",
    "community": "Our community organized a charity event last weekend.",
    "comparison": "In comparison, this phone is much cheaper.",
    "compensation": "The workers received compensation for overtime.",
    "competitor": "Each competitor trained hard for the race.",
    "complication": "An unexpected complication delayed the project.",
    "computerized": "The factory uses a computerized system for production.",
    "concentration": "Good concentration helps you study more effectively.",
    "condition": "The car is in excellent condition for its age.",
    "conference": "Doctors from around the world attended the conference.",
    "confidence": "Practice will help you build confidence.",
    "congratulate": "I want to congratulate you on your success!",
    "connection": "There is a strong connection between diet and health.",
    "considered": "She is considered one of the best students.",
    "consolidate": "The company decided to consolidate its offices.",
    "consonants": "English has twenty one consonants in its alphabet.",
    "constitution": "The constitution protects the rights of citizens.",
    "construction": "The construction of the new bridge will take two years.",
    "consumerism": "Consumerism has increased in recent decades.",
    "consumption": "Reducing energy consumption helps the environment.",
    "contemplation": "After much contemplation, she made her decision.",
    "continuation": "The movie is a continuation of the original story.",
    "contradiction": "There was a contradiction between his words and actions.",
    "contribution": "Her contribution to the project was very valuable.",
    "conventional": "He prefers conventional methods of teaching.",
    "conversation": "They had a long conversation about their future plans.",
    "cooperate": "The students learned to cooperate on group projects.",
    "cooperation": "International cooperation is needed to solve climate change.",
    "correction": "The teacher made a correction on my essay.",
    "correlation": "There is a correlation between exercise and good health.",
    "countable": "Apples and books are examples of countable nouns.",
    "creativity": "Creativity is important in art and design.",
    "cupboard": "Put the plates back in the cupboard please.",
    "cycling": "Cycling to work is good exercise and saves money.",
    "daughter": "Their daughter won first prize at the science fair.",
    "declaration": "The declaration was signed by all the leaders.",
    "decoration": "The holiday decoration made the room look festive.",
    "dedication": "Her dedication to her studies is truly admirable.",
    "definitely": "I will definitely be at the party tonight.",
    "deliberation": "After much deliberation, the jury reached a verdict.",
    "demonstrate": "The teacher will demonstrate how to solve the problem.",
    "demonstration": "The cooking demonstration attracted a large crowd.",
    "department": "She works in the marketing department.",
    "dependability": "Dependability is a quality employers look for.",
    "determination": "With determination, you can achieve your goals.",
    "determined": "She was determined to finish the marathon.",
    "development": "The development of the new app took six months.",
    "dictionaries": "There are many dictionaries available online.",
    "difficulty": "She had difficulty understanding the instructions.",
    "dining room": "The family gathered in the dining room for dinner.",
    "directional": "The directional signs helped us find our way.",
    "disadvantage": "The main disadvantage is the high cost.",
    "disagreement": "They resolved their disagreement through discussion.",
    "disappearing": "Many animal species are disappearing from the wild.",
    "disciplinary": "The school took disciplinary action against bullying.",
    "discontinued": "The product has been discontinued by the manufacturer.",
    "discouragement": "Do not let discouragement stop you from trying again.",
    "discoverable": "The hidden features are easily discoverable.",
    "discovered": "Scientists discovered a new species of butterfly.",
    "discriminate": "It is wrong to discriminate against anyone.",
    "discrimination": "We must fight against discrimination in all forms.",
    "discussion": "We had a productive discussion about the project.",
    "disgusting": "The spoiled food smelled absolutely disgusting.",
    "dishes": "Please help me wash the dishes after dinner.",
    "dislike": "I dislike getting up early on cold mornings.",
    "disobedience": "The child was punished for disobedience.",
    "dolphin": "We saw a dolphin jumping out of the water.",
    "down town": "We went down town to visit the new museum.",
    "eagle": "The eagle soared high above the mountains.",
    "earphones": "I forgot my earphones at home today.",
    "easily": "She can easily solve difficult math problems.",
    "economical": "This car is very economical on fuel.",
    "educational": "The documentary was both educational and entertaining.",
    "electrician": "We called an electrician to fix the wiring.",
    "elephant": "The elephant is the largest land animal.",
    "elimination": "The elimination round was very competitive.",
    "embarrassment": "She felt embarrassment after tripping on stage.",
    "emergency": "In an emergency, call the fire department immediately.",
    "emotional": "The farewell speech was very emotional.",
    "emphasizing": "The coach kept emphasizing the importance of teamwork.",
    "encouragement": "A few words of encouragement can make a big difference.",
    "encouraging": "The teacher gave encouraging feedback on the essay.",
    "endangered": "The panda is an endangered species.",
    "energetically": "The children played energetically in the schoolyard.",
    "engineer": "The engineer designed a new type of bridge.",
    "enjoyability": "The enjoyability of the game made it very popular.",
    "enjoyable": "The picnic was a very enjoyable experience.",
    "entertain": "The clown was hired to entertain the children.",
    "enthusiasm": "She showed great enthusiasm for the new project.",
    "environment": "We must protect the environment for future generations.",
    "environmental": "Environmental pollution is a serious global issue.",
    "equivalently": "Both methods work equivalently well.",
    "eraser": "I need an eraser to correct my mistake.",
    "especially": "I like all sports, especially basketball.",
    "establishment": "The establishment of the school was in nineteen fifty.",
    "estimation": "My estimation is that it will take two hours.",
    "evaluation": "The teacher gave a positive evaluation of the project.",
    "evening": "We usually have dinner in the evening at seven.",
    "everlasting": "Their everlasting friendship inspired many people.",
    "everywhere": "There were flowers everywhere in the garden.",
    "exaggerate": "Do not exaggerate when telling the story.",
    "exaggeration": "Saying it rained for a month is an exaggeration.",
    "exasperation": "She sighed in exasperation at the delay.",
    "excuse me": "Excuse me, could you tell me the time?",
    "exercise": "Regular exercise keeps you healthy and strong.",
    "expectation": "The film exceeded all our expectations.",
    "experimental": "The experimental treatment showed promising results.",
    "experimentation": "Scientific experimentation requires careful observation.",
    "experimenting": "The students are experimenting with different chemicals.",
    "explanation": "The teacher gave a clear explanation of the problem.",
    "explanatory": "The book includes explanatory notes at the end.",
    "exploitation": "The exploitation of natural resources must be controlled.",
    "extermination": "The extermination of pests required professional help.",
    "fabrication": "The story turned out to be a complete fabrication.",
    "facilitator": "The facilitator guided the group through the discussion.",
    "factory": "The factory produces over a thousand cars per day.",
    "fascinating": "The documentary about space was truly fascinating.",
    "fascination": "His fascination with science began at an early age.",
    "fashionable": "She always wears fashionable clothes.",
    "february": "February is the shortest month of the year.",
    "federation": "The federation includes members from many countries.",
    "fence": "We painted the fence white last weekend.",
    "festival": "The music festival attracted thousands of visitors.",
    "fire fighter": "The brave fire fighter rescued the family from the flames.",
    "fishing": "We went fishing at the lake on Sunday morning.",
    "flood": "The heavy rain caused a flood in the valley.",
    "fortification": "The old fortification protected the city for centuries.",
    "fortunate": "We are fortunate to live in a safe neighborhood.",
    "fruits": "Eating fresh fruits is good for your health.",
    "frustrating": "It is frustrating when the internet is slow.",
    "frustration": "He expressed his frustration with the delay.",
    "garage": "We parked the car in the garage.",
    "generosity": "Her generosity helped many people in need.",
    "geometrical": "The artist used geometrical shapes in the painting.",
    "graduation": "The whole family attended the graduation ceremony.",
    "grandchildren": "The grandparents love spending time with their grandchildren.",
    "granddaughter": "His granddaughter visits him every summer.",
    "grandfather": "My grandfather told us stories about his youth.",
    "green point": "The recycling center is located at Green Point.",
    "groceries": "We need to buy groceries for the week.",
    "guinea pig": "The children have a guinea pig as a class pet.",
    "hairbrush": "She used a hairbrush to untangle her hair.",
    "hairdresser": "I have an appointment with the hairdresser at noon.",
    "handles": "The suitcase has two strong handles.",
    "happiness": "Happiness comes from spending time with loved ones.",
    "hesitatingly": "She hesitatingly raised her hand to answer.",
    "hesitation": "Without hesitation, he jumped into the water to help.",
    "holidays": "We spent the holidays at the seaside.",
    "homework": "Remember to finish your homework before dinner.",
    "hospitality": "The hotel is known for its excellent hospitality.",
    "hospitalization": "The hospitalization lasted only three days.",
    "identification": "Please bring identification when you travel.",
    "images": "The website displays images from around the world.",
    "imaginary": "The child had an imaginary friend named Max.",
    "implementation": "The implementation of the new system took six months.",
    "impossible": "Nothing is impossible if you work hard enough.",
    "impression": "Her speech made a strong impression on the audience.",
    "improvement": "There has been a great improvement in her grades.",
    "improvisation": "Jazz music often involves improvisation.",
    "independence": "The country celebrated its independence day.",
    "independent": "She became independent after moving to the city.",
    "indication": "Dark clouds are an indication of rain.",
    "individually": "Each student was tested individually.",
    "industrial": "The industrial area is located outside the city.",
    "industrialization": "Industrialization changed the way people worked.",
    "influential": "She became one of the most influential leaders.",
    "informational": "The informational brochure was very helpful.",
    "infrastructure": "The city invested in improving its infrastructure.",
    "innovation": "Innovation drives progress in technology.",
    "innovative": "The company is known for its innovative products.",
    "inspiration": "Nature is a great source of inspiration for artists.",
    "inspirational": "The speech was truly inspirational.",
    "installation": "The installation of the new software was quick.",
    "instantaneous": "The response was almost instantaneous.",
    "institutional": "Institutional changes are needed to improve education.",
    "instructor": "The driving instructor was very patient.",
    "instrument": "She plays a musical instrument in the school band.",
    "instrumental": "Music was instrumental in bringing people together.",
    "insurance": "Car insurance is required by law in most countries.",
    "intellectual": "The intellectual debate lasted for hours.",
    "intelligent": "Dolphins are very intelligent animals.",
    "intention": "Her intention was to help, not to interfere.",
    "intentionality": "The intentionality behind the design was clear.",
    "internationalization": "The internationalization of business is increasing.",
    "interpretation": "His interpretation of the poem was very creative.",
    "interrelation": "The interrelation between health and diet is clear.",
    "interrogation": "The detective conducted an interrogation of the suspect.",
    "intervention": "Early intervention can prevent many health problems.",
    "interviewer": "The interviewer asked challenging questions.",
    "introduction": "The introduction to the book was very interesting.",
    "irregular": "The verb has an irregular past tense form.",
    "irresponsible": "It is irresponsible to leave litter in the park.",
    "irritating": "The constant noise was very irritating.",
    "jacket": "Put on your jacket because it is cold outside.",
    "jelly fish": "Be careful of jelly fish when swimming in the sea.",
    "jungle": "The jungle is home to many exotic animals.",
    "justification": "There is no justification for being rude to others.",
    "keyboard": "She types very fast on the keyboard.",
    "laboratory": "The students conducted experiments in the laboratory.",
    "laundromat": "I took my clothes to the laundromat to wash them.",
    "legitimately": "She legitimately earned her place on the team.",
    "liberation": "The liberation of the city was celebrated by everyone.",
    "lifestyle": "A healthy lifestyle includes exercise and good food.",
    "loudly": "The crowd cheered loudly when the team scored.",
    "lunchtime": "We always eat together at lunchtime.",
    "magazine": "She reads a fashion magazine every month.",
    "magnification": "The microscope provides high magnification.",
    "magnificent": "The view from the mountain top was magnificent.",
    "maintainable": "The code was written to be easily maintainable.",
    "manufacturing": "The manufacturing process was fully automated.",
    "marginalization": "We must fight against the marginalization of minorities.",
    "material": "The dress was made from a soft material.",
    "meaningful": "The gift was small but very meaningful.",
    "memorable": "Our trip to Italy was truly memorable.",
    "miscommunication": "The problem was caused by a miscommunication.",
    "misunderstand": "Please do not misunderstand what I am saying.",
    "modification": "The modification to the plan was approved.",
    "monkey": "The monkey swung from tree to tree.",
    "motivation": "Good grades are a strong motivation to study harder.",
    "mountains": "We went hiking in the mountains last weekend.",
    "multiplication": "Multiplication tables are important to memorize.",
    "multiplying": "She practiced multiplying large numbers.",
    "museum": "We visited the natural history museum on our field trip.",
    "mysterious": "The old house had a mysterious atmosphere.",
    "nationality": "People of every nationality are welcome here.",
    "necklace": "She wore a beautiful gold necklace to the dinner.",
    "negotiable": "The price is negotiable if you buy in bulk.",
    "negotiation": "The negotiation between the two companies lasted weeks.",
    "newspaper": "He reads the newspaper every morning with breakfast.",
    "noodles": "We ordered a bowl of noodles for lunch.",
    "notebook": "Write your notes in the notebook.",
    "november": "November is the month before December.",
    "octopus": "The octopus has eight long tentacles.",
    "office building": "The new office building has twenty floors.",
    "often": "I often go for a walk in the evening.",
    "operational": "The new system is now fully operational.",
    "opportunity": "This is a great opportunity to learn something new.",
    "organization": "The organization helps children in need.",
    "organizational": "Her organizational skills are excellent.",
    "orientation": "The orientation for new students is on Monday.",
    "outstanding": "She did an outstanding job on her presentation.",
    "paintings": "The gallery displayed paintings by local artists.",
    "parliament": "The new law was debated in parliament.",
    "participate": "All students are encouraged to participate in the event.",
    "participation": "Active participation helps you learn faster.",
    "particular": "Is there a particular book you are looking for?",
    "perception": "Perception of color varies from person to person.",
    "performance": "The orchestra gave a wonderful performance.",
    "perpetuation": "The perpetuation of this tradition is important.",
    "personality": "She has a warm and friendly personality.",
    "personalization": "The personalization of the gift made it special.",
    "personification": "The poem uses personification to describe the wind.",
    "pharmacy": "I need to pick up my prescription at the pharmacy.",
    "philosophical": "They had a deep philosophical discussion.",
    "photography": "Photography is her favorite hobby.",
    "police officer": "The police officer helped us find our way.",
    "population": "The population of the city is growing rapidly.",
    "possession": "The old photograph was her most treasured possession.",
    "possibility": "There is a possibility of rain tomorrow.",
    "post office": "I went to the post office to mail a letter.",
    "practically": "She practically lives at the library during exams.",
    "precaution": "Wearing a helmet is a safety precaution.",
    "precipitation": "The weather forecast predicts heavy precipitation.",
    "prediction": "His prediction about the weather was correct.",
    "predomination": "The predomination of technology in daily life is clear.",
    "preference": "Do you have a preference for tea or coffee?",
    "preparation": "Preparation for the exam took several weeks.",
    "presentation": "She gave an excellent presentation to the class.",
    "principal": "The principal of the school gave a welcome speech.",
    "probability": "The probability of winning the lottery is very low.",
    "production": "The production of the film took over a year.",
    "professional": "She is a professional dancer and performs worldwide.",
    "professionalism": "His professionalism impressed everyone at the meeting.",
    "professorship": "She was offered a professorship at the university.",
    "programming": "He learned computer programming at a young age.",
    "progression": "The progression of the disease was closely monitored.",
    "pronunciation": "Her pronunciation of French words is excellent.",
    "property": "They bought a property near the lake.",
    "proportional": "The reward should be proportional to the effort.",
    "protection": "Sunscreen provides protection from harmful rays.",
    "psychology": "She is studying psychology at the university.",
    "questionable": "The decision was considered questionable by many.",
    "questions": "The students asked many questions during the lesson.",
    "quickly": "She quickly finished her homework and went outside.",
    "rainbow": "A beautiful rainbow appeared after the storm.",
    "recognition": "He received recognition for his hard work.",
    "recognize": "I did not recognize her with her new hairstyle.",
    "recommendation": "The doctor gave a recommendation for a specialist.",
    "reconstruction": "The reconstruction of the bridge took two years.",
    "reflection": "She looked at her reflection in the mirror.",
    "regulatory": "The regulatory authorities approved the new medicine.",
    "remember": "Remember to bring your umbrella, it might rain.",
    "reputation": "The restaurant has an excellent reputation.",
    "reservation": "We made a reservation at the restaurant for eight.",
    "resolution": "Her New Year resolution was to read more books.",
    "responsibility": "Taking care of a pet is a big responsibility.",
    "responsible": "Each student is responsible for their own work.",
    "revolution": "The industrial revolution changed the world forever.",
    "sailing": "We went sailing on the lake last summer.",
    "sales assistant": "The sales assistant helped me choose the right shoes.",
    "sandcastle": "The children built a sandcastle on the beach.",
    "saturday": "We usually go shopping on Saturday morning.",
    "saxophone": "He plays the saxophone in the jazz band.",
    "scientific": "The scientific experiment produced interesting results.",
    "scientist": "The scientist discovered a new type of bacteria.",
    "scissors": "Use scissors to cut along the dotted line.",
    "sea lion": "We watched the sea lion perform at the aquarium.",
    "sensational": "The news about the discovery was sensational.",
    "sensitization": "The campaign focused on sensitization about recycling.",
    "separation": "The separation of the two friends was difficult.",
    "shopping": "We went shopping for new school supplies.",
    "shoulder": "He carried the heavy bag on his shoulder.",
    "simplicity": "The beauty of the design lies in its simplicity.",
    "simultaneously": "She can speak two languages simultaneously.",
    "skateboarding": "Skateboarding is a popular sport among teenagers.",
    "skirt": "She wore a blue skirt to the party.",
    "sneakers": "He bought a new pair of sneakers for the race.",
    "snowboarding": "We went snowboarding in the mountains during winter.",
    "sophisticated": "The new technology is very sophisticated.",
    "specifically": "I specifically asked for no onions on my burger.",
    "specification": "Please read the specification before assembling.",
    "spirituality": "Spirituality is important to many people.",
    "stand up": "Please stand up when the teacher enters the room.",
    "statistical": "The statistical analysis confirmed the hypothesis.",
    "statistically": "Statistically, the results were very significant.",
    "steering wheel": "Hold the steering wheel firmly while driving.",
    "stimulating": "The debate was intellectually stimulating.",
    "supermarket": "We buy our groceries at the supermarket.",
    "supplementary": "The teacher provided supplementary reading materials.",
    "surprising": "The result of the election was very surprising.",
    "sweater": "Put on a warm sweater because it is chilly.",
    "telecommunication": "The telecommunication industry is growing rapidly.",
    "television": "We watched a documentary on television last night.",
    "terminology": "Medical terminology can be difficult to learn.",
    "territory": "The animal defended its territory fiercely.",
    "thailand": "We traveled to Thailand for our summer holiday.",
    "theater": "We went to the theater to see a play.",
    "theoretical": "The theoretical model was tested with experiments.",
    "thirty three": "She will be thirty three years old next month.",
    "thursday": "The meeting is scheduled for Thursday afternoon.",
    "tiring": "The long hike was very tiring but rewarding.",
    "tomatoes": "We grow tomatoes in our garden every summer.",
    "tomorrow": "We will visit the museum tomorrow morning.",
    "toothbrush": "Replace your toothbrush every three months.",
    "traditionally": "The festival has traditionally been held in June.",
    "train station": "We arrived at the train station just in time.",
    "translational": "The translational research led to a new treatment.",
    "transmission": "The transmission of the disease can be prevented.",
    "transparency": "Transparency in government builds public trust.",
    "transportation": "Public transportation is the most efficient way to travel.",
    "umbrella": "Take an umbrella in case it rains.",
    "uncountable": "Water and rice are examples of uncountable nouns.",
    "understand": "I understand the instructions clearly now.",
    "united kingdom": "The United Kingdom includes England, Scotland, and Wales.",
    "videogames": "Playing too many videogames can affect your sleep.",
    "volcano": "The volcano erupted and sent ash into the sky.",
    "volleyball": "We played volleyball on the beach all afternoon.",
    "vulnerability": "Discussing vulnerability takes a lot of courage.",
    "waitress": "The waitress brought our food quickly.",
    "waking up": "Waking up early gives you more time in the day.",
    "warming": "Global warming is a serious environmental concern.",
    "warning": "The warning sign said the road was closed.",
    "wheelchair": "The building has ramps for wheelchair access.",
    "whistle": "The referee blew the whistle to start the game.",
    "white": "The white snow covered the entire landscape.",
    "workplace": "Safety in the workplace is very important.",
}


# ==================== WEEKLY WORD GROUPS ====================
# Fixed to exactly 4 weeks for all groups
NUM_WEEKS = 4

def _chunk_into_weeks(words, num_weeks=4):
    """Divide words into exactly num_weeks chunks, distributing evenly."""
    if not words:
        return [[] for _ in range(num_weeks)]
    chunk_size = len(words) // num_weeks
    remainder = len(words) % num_weeks
    weeks = []
    start = 0
    for i in range(num_weeks):
        end = start + chunk_size + (1 if i < remainder else 0)
        weeks.append(words[start:end])
        start = end
    return weeks

WORDS_PER_WEEK = 30  # kept for backward compat but not used for chunking

def _chunk(words, chunk_size):
    """Divide words into weekly chunks (backward compat)."""
    return [words[i:i+chunk_size] for i in range(0, len(words), chunk_size)]

def _chunk_balanced(easy, medium, hard, min_per_difficulty=10):
    """Divide words into weeks ensuring minimum words per difficulty."""
    max_weeks = min(
        len(easy) // min_per_difficulty if easy else 0,
        len(medium) // min_per_difficulty if medium else 0,
        len(hard) // min_per_difficulty if hard else 0
    )
    if max_weeks == 0:
        max_weeks = 1
    weeks = []
    for week_num in range(max_weeks):
        easy_start = week_num * (len(easy) // max_weeks)
        easy_end = (week_num + 1) * (len(easy) // max_weeks)
        if week_num == max_weeks - 1:
            easy_end = len(easy)
        medium_start = week_num * (len(medium) // max_weeks)
        medium_end = (week_num + 1) * (len(medium) // max_weeks)
        if week_num == max_weeks - 1:
            medium_end = len(medium)
        hard_start = week_num * (len(hard) // max_weeks)
        hard_end = (week_num + 1) * (len(hard) // max_weeks)
        if week_num == max_weeks - 1:
            hard_end = len(hard)
        weeks.append({
            "week": week_num + 1,
            "easy": easy[easy_start:easy_end],
            "medium": medium[medium_start:medium_end],
            "hard": hard[hard_start:hard_end],
        })
    return weeks, max_weeks

EASY_WEEKS = _chunk_into_weeks(EASY_WORDS, NUM_WEEKS)
MEDIUM_WEEKS = _chunk_into_weeks(MEDIUM_WORDS, NUM_WEEKS)
HARD_WEEKS = _chunk_into_weeks(HARD_WORDS, NUM_WEEKS)

WEEKS_BY_DIFFICULTY = {
    "easy": EASY_WEEKS,
    "medium": MEDIUM_WEEKS,
    "hard": HARD_WEEKS,
}

# ==================== RANKED MODE ====================
RANKED_WEEK = 1

# ==================== GROUP CONFIG ====================
VALID_GROUPS = ["group1", "group2", "group3", "group4", "tournament"]

GROUP_CONFIG = {
    "group1": {
        "label": "Group 1",
        "ranked_week": 1,
        "words": {
            "easy": _GROUP1_EASY,
            "medium": _GROUP1_MEDIUM,
            "hard": _GROUP1_HARD,
        },
    },
    "group2": {
        "label": "Group 2",
        "ranked_week": 1,
        "words": {
            "easy": _GROUP2_EASY,
            "medium": _GROUP2_MEDIUM,
            "hard": _GROUP2_HARD,
        },
    },
    "group3": {
        "label": "Group 3",
        "ranked_week": 1,
        "words": {
            "easy": _GROUP3_EASY,
            "medium": _GROUP3_MEDIUM,
            "hard": _GROUP3_HARD,
        },
    },
    "group4": {
        "label": "Group 4",
        "ranked_week": 1,
        "words": {
            "easy": _GROUP4_EASY,
            "medium": _GROUP4_MEDIUM,
            "hard": _GROUP4_HARD,
        },
    },
    "tournament": {
        "label": "Tournament",
        "ranked_week": 1,
        "words": {
            "easy": _TOURNAMENT_EASY,
            "medium": _TOURNAMENT_MEDIUM,
            "hard": _TOURNAMENT_HARD,
        },
    },
}


# ==================== API FUNCTIONS ====================

def get_group_words(group, difficulty):
    """Return the full word list for a group + difficulty."""
    cfg = GROUP_CONFIG.get(group, GROUP_CONFIG["group1"])
    custom = cfg.get("words", {})
    if difficulty in custom and custom[difficulty]:
        return custom[difficulty]
    # Global fallback (group1)
    if difficulty == "hard":
        return HARD_WORDS
    elif difficulty == "medium":
        return MEDIUM_WORDS
    return EASY_WORDS


def get_group_weeks(group, difficulty):
    """Return weekly chunks for a group + difficulty. Always 4 weeks."""
    words = get_group_words(group, difficulty)
    return _chunk_into_weeks(words, NUM_WEEKS)


def get_words_for_week(difficulty, week, group="group1"):
    """Return word list for a given difficulty and week (1-indexed). Week 0 = all words."""
    if week == 0:
        return get_group_words(group, difficulty)
    weeks = get_group_weeks(group, difficulty)
    idx = max(0, min(week - 1, len(weeks) - 1))
    return weeks[idx]


def get_week_count(difficulty, group="group1"):
    """Return number of weeks available for a difficulty."""
    return NUM_WEEKS


def get_ranked_words(group="group1"):
    """Return the word pool for ranked mode (only the current week's words)."""
    cfg = GROUP_CONFIG.get(group, GROUP_CONFIG["group1"])
    rw = cfg.get("ranked_week", RANKED_WEEK)
    easy = get_words_for_week("easy", rw, group)
    medium = get_words_for_week("medium", rw, group)
    hard = get_words_for_week("hard", rw, group)
    return {"easy": easy, "medium": medium, "hard": hard}


def get_bomb_words(group="group1"):
    """Return all hard words from all weeks for bomb word selection."""
    return get_group_words(group, "hard")


def get_bomb_words_by_difficulty(group="group1", difficulty="hard"):
    """Return hard words only for bomb word selection (all groups)."""
    return get_bomb_words(group)


def get_words_with_weeks(group="group1"):
    """Return all words with their week numbers for review sorting."""
    result = {"easy": [], "medium": [], "hard": []}
    for difficulty in ["easy", "medium", "hard"]:
        weeks = get_group_weeks(group, difficulty)
        for week_num, week_words in enumerate(weeks, 1):
            for word in week_words:
                result[difficulty].append({"word": word, "week": week_num})
    return result


def get_group_label(group):
    """Return display label for a group."""
    cfg = GROUP_CONFIG.get(group, GROUP_CONFIG["group1"])
    return cfg.get("label", group)


def format_spelling_text(word):
    """Format a word for letter-by-letter TTS spelling."""
    parts = []
    for ch in str(word):
        if ch.isalpha():
            parts.append(ch.upper())
        elif ch.isdigit():
            parts.append(ch)
        elif ch.isspace():
            parts.append(" ")
    out = []
    for p in parts:
        if p == " ":
            if out and out[-1] != ", ":
                out.append(", ")
            continue
        out.append(p)
        out.append("... ")
    return "".join(out).strip()


# Combined for backward compat
WORDS = EASY_WORDS + HARD_WORDS
